import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Geist_Mono, Jost, Kaushan_Script, Poppins } from "next/font/google";
import { notFound } from "next/navigation";
import { isLocale, locales } from "../../../i18n";
import "../globals.css";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const kaushanScript = Kaushan_Script({
  variable: "--font-kaushan-script",
  subsets: ["latin"],
  weight: ["400"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{ children: React.ReactNode; params: Promise<{ locale: string }> }>) {
  const { locale } = await params;
  if (!isLocale(locale)) {
    notFound();
  }
  const messages = await getMessages({ locale });

  // Create CSS variables string for fonts
  const fontVars = `${jost.variable} ${geistMono.variable} ${kaushanScript.variable} ${poppins.variable}`;

  return (
    <NextIntlClientProvider messages={messages} locale={locale}>
      <div className={fontVars} style={{ display: "contents" }}>
        {children}
      </div>
    </NextIntlClientProvider>
  );
}
